### ISSUE TITLE
Introducing mnemonic so early is confusing

### ISSUE THREAD

**Issue by retrohacker** [frdwrd/documentation#3]
https://github.com/frdwrd/documentation/blob/master/02-storj-object.md

Since it is an optional parameter, perhaps we leave it out of our examples until it is introduced. Right now we say "we'll come back to this later," our takeaway was that we needed to have mnemonic to get the sample to run.

**Comment by frdwrd** [comment]
709e419 removes it from chapter 2.

I'm thinking about writing another section in chapter 2 that covers making a mnemonic, but not how they function, as a lot of the stuff in chapter 3 won't work right without a mnemonic.

**Comment by retrohacker** [comment]
I'm actually working on a PR now that introduces it in chapter 3. 3 seems like a good fit since the focus is on files, and the mnemonic is needed for file operations vs. the key being used for bucket operations (when authing against the bridge).

**Comment by frdwrd** [comment]
sounds good

**Comment by frdwrd** [comment]
Addressed by #9 ?
